# -*- coding: UTF-8 -*-

#mongoDB config
MONGO_SVRIP = "127.0.0.1"
MONGO_SVRPORT = 27017 
MONGO_PPTDB = 'LivePPT-PPT'
MONGO_IMGDB = 'LivePPT-Img'

#redis config
REDIS_SVRIP = "127.0.0.1"
REDIS_SVRPORT = 6379

PPT_CONVERT_REQMQ = 'LivePPT-Convert-ReqMq'
PPT_CONVERT_RESPMQ = 'LivePPT-Convert-RespMq'


UTF8_ENCODING = "UTF-8"

POWERPOINT_APPLICATION_NAME = "PowerPoint.Application"
